name: EmployeeFrontend DevsOps Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 Download the source code
        uses: actions/checkout@v3.5.3

      - name: Setup 2 install Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18.16.1'
      - name: step 3 install Dependencies
        run: npm install 

      - name: step 4 SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{secrets.SONAR_TOKEN}}
        with:
          args: >
            -Dsonar.organization=nawaf7456 
            -Dsonar.projectKey=nawaf7456_employeefrontend-fursan-track3 
            -Dsonar.sources=. 
            -Dsonar.host.url=https://sonarcloud.io
      
  
  npm-audit:
    runs-on: ubuntu-latest
    name: NPM Audit
    steps:
      - name: step 1 download the source code
        uses: actions/checkout@v3.5.3

      - name: step 2 install Node.js
        uses: actions/setup-node@v3.7.0
      
        with:
          node-version: '18.16.1'

      - name: step 3 install dependencies
        run: npm install

      - name: step 4 npm audit scan 
        run: npm audit --json > npm-audit-result.json
        continue-on-error: true

      - name: step 5 upload npm audit scan report to github
        uses: actions/upload-artifact@v3
        
        with:
          name: npm-audit-result
          path: npm-audit-result.json


          



          
          